version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "registro"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-92qkponzv6aq"
s3_prefix = "registro"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
